project_id = "dalarhopratsgzmmzhxx"

[functions.send-email-custom]
verify_jwt = false

[functions.check-dns-mx]
verify_jwt = false

[functions.process-queue]
verify_jwt = false

[functions.reprocess-upgrade]
verify_jwt = false

[functions.track-email-open]
verify_jwt = false

[functions.reset-daily-credits]
verify_jwt = false

[functions.convert-resume]
verify_jwt = false

[functions.process-radar]
verify_jwt = false